name: Compile binaries (Windows x64 only)
on:
  workflow_dispatch:

jobs:
  windows-x64:
    runs-on: windows-latest

    steps:
    - name: Enable long paths
      run: git config --system core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install Ninja
      run: choco install ninja

    - name: Build module
      run: make optimized

    - name: Run tests
      run: |
        npm config set script-shell bash
        npm test

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: skia-node-windows-x64
        path: lib/skia.node
        if-no-files-found: error
